scara_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint1
    pid: {p: 1, i: 0.0, d: 0.1}
  joint2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint2
    pid: {p: 1, i: 0.0, d: 0.1}
  joint3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.01, d: 0.1}