scara_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 200.0, i: 0.0, d: 120.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 55.0, i: 0.0, d: 30.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 50.0, i: 0.0, d: 10.0}

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: {p: 50.0, i: 0.0, d: 30.0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint2
    pid: {p: 50.0, i: 0.0, d: 30.0}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint3
    pid: {p: 50.0, i: 0.0, d: 30.0}