name: Noetic Test
run-name: Build and Test
on:
  push:
    branches:
      - main
      - add_ci
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: scara_robot
          target-ros1-distro: noetic
